[package]
version = "0.1.0"
name = "fibonacci-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "2.0.0"
fibonacci-lib = { path = "../lib" }
sha3 = "0.10.8"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
